<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Currency;

class CurrenciesSeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            ['name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$'],
            ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€'],
            ['name' => 'British Pound', 'code' => 'GBP', 'symbol' => '£'],
            ['name' => 'Japanese Yen', 'code' => 'JPY', 'symbol' => '¥'],
            ['name' => 'Australian Dollar', 'code' => 'AUD', 'symbol' => 'A$'],
            ['name' => 'Canadian Dollar', 'code' => 'CAD', 'symbol' => 'C$'],
            ['name' => 'Swiss Franc', 'code' => 'CHF', 'symbol' => 'CHF'],
            ['name' => 'Chinese Yuan', 'code' => 'CNY', 'symbol' => '¥'],
            ['name' => 'Swedish Krona', 'code' => 'SEK', 'symbol' => 'kr'],
            ['name' => 'New Zealand Dollar', 'code' => 'NZD', 'symbol' => 'NZ$'],
            ['name' => 'Mexican Peso', 'code' => 'MXN', 'symbol' => '$'],
            ['name' => 'Singapore Dollar', 'code' => 'SGD', 'symbol' => 'S$'],
            ['name' => 'Hong Kong Dollar', 'code' => 'HKD', 'symbol' => 'HK$'],
            ['name' => 'Norwegian Krone', 'code' => 'NOK', 'symbol' => 'kr'],
            ['name' => 'South Korean Won', 'code' => 'KRW', 'symbol' => '₩'],
            ['name' => 'Turkish Lira', 'code' => 'TRY', 'symbol' => '₺'],
            ['name' => 'Russian Ruble', 'code' => 'RUB', 'symbol' => '₽'],
            ['name' => 'Indian Rupee', 'code' => 'INR', 'symbol' => '₹'],
            ['name' => 'Brazilian Real', 'code' => 'BRL', 'symbol' => 'R$'],
            ['name' => 'South African Rand', 'code' => 'ZAR', 'symbol' => 'R'],
            ['name' => 'Polish Zloty', 'code' => 'PLN', 'symbol' => 'zł'],
            ['name' => 'Israeli Shekel', 'code' => 'ILS', 'symbol' => '₪'],
            ['name' => 'Czech Koruna', 'code' => 'CZK', 'symbol' => 'Kč'],
            ['name' => 'Danish Krone', 'code' => 'DKK', 'symbol' => 'kr'],
            ['name' => 'Hungarian Forint', 'code' => 'HUF', 'symbol' => 'Ft'],
            ['name' => 'Romanian Leu', 'code' => 'RON', 'symbol' => 'lei'],
            ['name' => 'Bulgarian Lev', 'code' => 'BGN', 'symbol' => 'лв'],
            ['name' => 'Croatian Kuna', 'code' => 'HRK', 'symbol' => 'kn'],
            ['name' => 'Ukrainian Hryvnia', 'code' => 'UAH', 'symbol' => '₴'],
            ['name' => 'Thai Baht', 'code' => 'THB', 'symbol' => '฿'],
            ['name' => 'Malaysian Ringgit', 'code' => 'MYR', 'symbol' => 'RM'],
            ['name' => 'Indonesian Rupiah', 'code' => 'IDR', 'symbol' => 'Rp'],
            ['name' => 'Philippine Peso', 'code' => 'PHP', 'symbol' => '₱'],
            ['name' => 'Vietnamese Dong', 'code' => 'VND', 'symbol' => '₫'],
            ['name' => 'Argentine Peso', 'code' => 'ARS', 'symbol' => '$'],
            ['name' => 'Chilean Peso', 'code' => 'CLP', 'symbol' => '$'],
            ['name' => 'Colombian Peso', 'code' => 'COP', 'symbol' => '$'],
            ['name' => 'Peruvian Sol', 'code' => 'PEN', 'symbol' => 'S/'],
            ['name' => 'Uruguayan Peso', 'code' => 'UYU', 'symbol' => '$U'],
            ['name' => 'Venezuelan Bolívar', 'code' => 'VES', 'symbol' => 'Bs.S'],
            ['name' => 'Egyptian Pound', 'code' => 'EGP', 'symbol' => '£'],
            ['name' => 'Moroccan Dirham', 'code' => 'MAD', 'symbol' => 'DH'],
            ['name' => 'Tunisian Dinar', 'code' => 'TND', 'symbol' => 'DT'],
            ['name' => 'Algerian Dinar', 'code' => 'DZD', 'symbol' => 'DA'],
            ['name' => 'Libyan Dinar', 'code' => 'LYD', 'symbol' => 'LD'],
            ['name' => 'Sudanese Pound', 'code' => 'SDG', 'symbol' => 'SD'],
            ['name' => 'Ethiopian Birr', 'code' => 'ETB', 'symbol' => 'Br'],
            ['name' => 'Kenyan Shilling', 'code' => 'KES', 'symbol' => 'KSh'],
            ['name' => 'Ugandan Shilling', 'code' => 'UGX', 'symbol' => 'USh'],
            ['name' => 'Tanzanian Shilling', 'code' => 'TZS', 'symbol' => 'TSh'],
            ['name' => 'Rwandan Franc', 'code' => 'RWF', 'symbol' => 'RF'],
            ['name' => 'Ghanaian Cedi', 'code' => 'GHS', 'symbol' => 'GH₵'],
            ['name' => 'Nigerian Naira', 'code' => 'NGN', 'symbol' => '₦'],
            ['name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'CFA'],
            ['name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'FCFA'],
            ['name' => 'Botswana Pula', 'code' => 'BWP', 'symbol' => 'P'],
            ['name' => 'Namibian Dollar', 'code' => 'NAD', 'symbol' => 'N$'],
            ['name' => 'Zambian Kwacha', 'code' => 'ZMW', 'symbol' => 'ZK'],
            ['name' => 'Zimbabwean Dollar', 'code' => 'ZWL', 'symbol' => 'Z$'],
            ['name' => 'Saudi Riyal', 'code' => 'SAR', 'symbol' => '﷼'],
            ['name' => 'UAE Dirham', 'code' => 'AED', 'symbol' => 'DH'],
            ['name' => 'Qatari Riyal', 'code' => 'QAR', 'symbol' => 'QR'],
            ['name' => 'Kuwaiti Dinar', 'code' => 'KWD', 'symbol' => 'KD'],
            ['name' => 'Bahraini Dinar', 'code' => 'BHD', 'symbol' => 'BD'],
            ['name' => 'Omani Rial', 'code' => 'OMR', 'symbol' => 'RO'],
            ['name' => 'Jordanian Dinar', 'code' => 'JOD', 'symbol' => 'JD'],
            ['name' => 'Lebanese Pound', 'code' => 'LBP', 'symbol' => 'L£'],
            ['name' => 'Syrian Pound', 'code' => 'SYP', 'symbol' => '£S'],
            ['name' => 'Iraqi Dinar', 'code' => 'IQD', 'symbol' => 'ID'],
            ['name' => 'Iranian Rial', 'code' => 'IRR', 'symbol' => '﷼'],
            ['name' => 'Afghan Afghani', 'code' => 'AFN', 'symbol' => '؋'],
            ['name' => 'Pakistani Rupee', 'code' => 'PKR', 'symbol' => 'Rs'],
            ['name' => 'Bangladeshi Taka', 'code' => 'BDT', 'symbol' => '৳'],
            ['name' => 'Sri Lankan Rupee', 'code' => 'LKR', 'symbol' => 'Rs'],
            ['name' => 'Nepalese Rupee', 'code' => 'NPR', 'symbol' => 'Rs'],
            ['name' => 'Bhutanese Ngultrum', 'code' => 'BTN', 'symbol' => 'Nu'],
            ['name' => 'Maldivian Rufiyaa', 'code' => 'MVR', 'symbol' => 'Rf'],
            ['name' => 'Kazakhstani Tenge', 'code' => 'KZT', 'symbol' => '₸'],
            ['name' => 'Uzbekistani Som', 'code' => 'UZS', 'symbol' => 'soʼm'],
            ['name' => 'Turkmenistani Manat', 'code' => 'TMT', 'symbol' => 'T'],
            ['name' => 'Tajikistani Somoni', 'code' => 'TJS', 'symbol' => 'SM'],
            ['name' => 'Kyrgyzstani Som', 'code' => 'KGS', 'symbol' => 'лв'],
            ['name' => 'Mongolian Tugrik', 'code' => 'MNT', 'symbol' => '₮'],
            ['name' => 'North Korean Won', 'code' => 'KPW', 'symbol' => '₩'],
            ['name' => 'Cambodian Riel', 'code' => 'KHR', 'symbol' => '៛'],
            ['name' => 'Laotian Kip', 'code' => 'LAK', 'symbol' => '₭'],
            ['name' => 'Myanmar Kyat', 'code' => 'MMK', 'symbol' => 'K'],
            ['name' => 'Brunei Dollar', 'code' => 'BND', 'symbol' => 'B$'],
            ['name' => 'East Caribbean Dollar', 'code' => 'XCD', 'symbol' => 'EC$'],
            ['name' => 'Barbadian Dollar', 'code' => 'BBD', 'symbol' => 'Bds$'],
            ['name' => 'Jamaican Dollar', 'code' => 'JMD', 'symbol' => 'J$'],
            ['name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD', 'symbol' => 'TT$'],
            ['name' => 'Bahamian Dollar', 'code' => 'BSD', 'symbol' => 'B$'],
            ['name' => 'Belize Dollar', 'code' => 'BZD', 'symbol' => 'BZ$'],
            ['name' => 'Costa Rican Colón', 'code' => 'CRC', 'symbol' => '₡'],
            ['name' => 'Guatemalan Quetzal', 'code' => 'GTQ', 'symbol' => 'Q'],
            ['name' => 'Honduran Lempira', 'code' => 'HNL', 'symbol' => 'L'],
            ['name' => 'Nicaraguan Córdoba', 'code' => 'NIO', 'symbol' => 'C$'],
            ['name' => 'Panamanian Balboa', 'code' => 'PAB', 'symbol' => 'B/.'],
            ['name' => 'Cuban Peso', 'code' => 'CUP', 'symbol' => '$'],
            ['name' => 'Dominican Peso', 'code' => 'DOP', 'symbol' => 'RD$'],
            ['name' => 'Haitian Gourde', 'code' => 'HTG', 'symbol' => 'G'],
            ['name' => 'Paraguayan Guaraní', 'code' => 'PYG', 'symbol' => 'Gs'],
            ['name' => 'Bolivian Boliviano', 'code' => 'BOB', 'symbol' => 'Bs'],
            ['name' => 'Ecuadorian Sucre', 'code' => 'ECS', 'symbol' => 'S/.'],
            ['name' => 'Guyanese Dollar', 'code' => 'GYD', 'symbol' => 'G$'],
            ['name' => 'Surinamese Dollar', 'code' => 'SRD', 'symbol' => 'Sr$'],
            ['name' => 'Falkland Islands Pound', 'code' => 'FKP', 'symbol' => '£'],
            ['name' => 'Saint Helena Pound', 'code' => 'SHP', 'symbol' => '£'],
            ['name' => 'Gibraltar Pound', 'code' => 'GIP', 'symbol' => '£'],
            ['name' => 'Icelandic Króna', 'code' => 'ISK', 'symbol' => 'kr'],
            ['name' => 'Faroese Króna', 'code' => 'FOK', 'symbol' => 'kr'],
            ['name' => 'Greenlandic Krone', 'code' => 'GLK', 'symbol' => 'kr']
        ];

        foreach ($currencies as $currency) {
            Currency::create($currency);
        }
    }
}